config/routes.rb
Rails.application.routes.draw do
  concern :autocompletable do
    collection do
      get :autocomplete
    end
  end

  concern :movable do
    member do
      patch :move_up
      patch :move_down
    end
  end

  concern :customizable do
    member do
      get :customize
      patch :customize, action: :apply_customization
    end
  end

  concern :taggable do
    member do
      patch :tag
      patch :untag
    end
  end

  concern :batch_processable do
    collection do
      patch :batch, action: :batch_process, as: :batch_process
    end
  end

  get 'sitemap.xml', to: 'sitemaps#index', as: :sitemaps, format: 'xml'
  get 'sitemap.:page.xml', to: 'sitemaps#show', as: :sitemap, format: 'xml'

  # Downloads
  scope 'files', constraints: { filename: /.*/ } do
    get 'images/download/:filename' => 'image/styles#download', as: :download_image_style
    get 'download/:filename' => 'attachments#download', as: :download_attachment
    get ':filename' => 'attachments#show', as: :attachment
  end

  scope '(:locale)', constraints: { locale: /[a-z]{2}/ } do
    scope constraints: Router::LocaleConstraint.new do
      namespace :admin do
        scope controller: :sessions do
          get :login, action: :new
          post :login, action: :create
          match :logout, action: :destroy, via: %i(get delete)
        end

        scope '(:translations)', constraints: { translations: /[a-z]{2}/ } do
          scope constraints: Router::LocaleConstraint.new(:translations) do
            get :search, controller: :search, action: :show

            namespace :editor do
              with_options only: [:show, :create, :update] do |r|
                r.resource :link
                r.resource :image
              end
            end

            namespace :stats do
              get 'disk_usage', to: 'disk_usage#index', as: :disk_usage

              scope :traffic, controller: :traffic do
                root action: :index, as: :traffic
                patch :reset, as: :reset_traffic
              end

              scope :downloads, controller: :downloads do
                root action: :index, as: :downloads
                scope '(:type)' do
                  get :total, as: :total_downloads
                  get ':year/:month', action: :month, as: :monthly_downloads, year: /[0-9]+/, month: /[0-9]+/
                  get ':year', action: :year, as: :yearly_downloads, year: /[0-9]+/
                end
                get :referers, as: :download_referers
              end

              scope :visits, controller: :visits do
                root action: :index, as: :visits
                get :total, as: :total_visits
                get ':year/:month', action: :month, as: :monthly_visits, year: /[0-9]+/, month: /[0-9]+/
                get ':year', action: :year, as: :yearly_visits, year: /[0-9]+/
              end
            end

            resource :account, except: %i(new create) do
              get :edit_password
              patch :update_password
              patch :update_preferences
            end

            resources :attachments, except: %i(new create show),
                                    concerns: :batch_processable do
              collection do
                match :upload, via: %i(post patch)
              end
              member do
                get :download
              end
              patch :convert_to_image, on: :member
            end

            resources :clients, only: %i(index edit update)

            resources :images, except: %i(new create), concerns: [:autocompletable,:customizable, :batch_processable, :taggable] do
              resources :styles, controller: :'image/styles', concerns: [:customizable, :movable, :batch_processable] do
                collection do
                  match :upload, via: %i(post patch)
                  delete :destroy_multiple
                end
              end
              resources :attachments, as: :attachments, controller: :'image/attachments', concerns: %i(movable batch_processable) do
                match :upload, on: :collection, via: %i(post patch)
              end
              resources :shop_links, controller: :'image/shop_links', except: %i(index show)
              collection do
                match :upload, via: %i(post patch)
                patch :associate_owner, action: :associate_owner, as: :associate_owner_with
                patch :associate_tags, action: :associate_tags, as: :associate_tags_with
              end
              member do
                get :pages
                get :download
                get :dimensions
                patch :convert_to_attachment
              end
            end

            resources :projects, concerns: [:autocompletable, :batch_processable, :taggable] do
              resources :images, controller: :'project/images', only: :destroy, concerns: [:movable, :batch_processable] do
                collection do
                  match :upload, via: %i(post patch)
                end
              end
              member do
                get :pages
                get :assign_images, as: :assign_images_to
                post :assign_images, action: :attach_images, as: :attach_images_to
              end
            end

            resources :providers, except: :show

            resources :messages, only: [:index, :show, :destroy] do
              collection do
                delete :destroy_multiple
              end
              member do
                patch :mark_read
                patch :mark_unread
              end
            end

            resources :pages, except: :new, concerns: [:autocompletable, :movable] do
              resources :children, controller: :pages, only: :new do
                get ':page_type', on: :new, action: :new, as: :typed
              end
              resources :regions, controller: :'page/regions', only: [:index, :edit, :update, :destroy] do
                patch :update_multiple, on: :collection
              end
              resource :image, controller: :'page/images', only: %i(new create)
              resource :contact_form, controller: :'page/contact_forms', only: [:edit, :update]
              resource :project, controller: :'page/projects', only: %i(new create)
              resource :redirection, controller: :'page/redirections', only: [:edit, :update]
              collection do
                get :tree
              end
              member do
                patch :move
                patch :publish
                patch :hide
                patch :enable_in_menu
                patch :disable_in_menu
                patch 'change_template/:template_id', action: :change_template, as: :change_template
              end
            end

            resources :redirections, only: [] do
              get :translation_fields, on: :collection
            end

            resources :tags, only: :index

            resources :templates, except: :new, concerns: :movable do
              resources :region_definitions, controller: :'template/region_definitions', except: [:index, :show], concerns: :movable
              get ':template_type', on: :new, action: :new, as: :typed
              collection do
                get 'types/:template_type', action: :index, as: :typed
                delete :destroy_multiple
              end
              member do
                delete 'destroy_region/:label', action: :destroy_region, as: :destroy_region
              end
            end

            resources :users do
              resources :social_links, controller: :'user/social_links', except: :show, concerns: :movable
              member do
                get :edit_password
                patch :update_password
              end
            end

            root to: redirect('/admin/pages')
          end
        end
      end

      # Legacy URLs that have changed permanently (HTTP 301)
      get 'image/:slug', to: redirect { |params, request|
        page = Page.images.find_by!('slug = ?', params[:slug])
        "/#{page.path}"
      }
      get 'category/:slug(/:page)', page: /\d/, to: redirect { |params, request|
                                      slug = params[:slug].split(',').first
                                      page = Page.contents.find_by!('slug = ?', slug)
                                      url = "/#{page.path}"
                                      page_index = params[:page].to_i
                                      url << "?page=#{page_index}" if page_index > 1
                                      url
                                    }

      get 'pic-:slug.:format', to: redirect { |params, request|
        page = Page.images.find_by!('slug = ?', params[:slug])
        page.image.asset.url(:public)
      }

      # Permalinks
      get ':id' => 'page/permalinks#show', as: :page_permalink, id: /[A-Z0-9]{6}/i
    end
  end
end

app/models/attachment/translation.rb
# == Schema Information
#
# Table name: attachment_translations
#
#  id            :integer          not null, primary key
#  attachment_id :integer          not null
#  locale        :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  title         :string
#  description   :text
#

class Attachment < ActiveRecord::Base
  class Translation < Globalize::ActiveRecord::Translation
    include UniquelyTranslated

    acts_as_uniquely_translated :attachment_id

    sanitizes :title, with: :squish

    validates :title, presence: true
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  first_name                      :string
#  last_name                       :string
#  created_at                      :datetime
#  updated_at                      :datetime
#  preferences                     :text
#  email                           :string           not null
#  crypted_password                :string           not null
#  salt                            :string           not null
#  remember_me_token               :string
#  remember_me_token_expires_at    :datetime
#  reset_password_token            :string
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  failed_logins_count             :integer          default(0)
#  lock_expires_at                 :datetime
#  unlock_token                    :string
#  last_login_at                   :datetime
#  last_logout_at                  :datetime
#  last_activity_at                :datetime
#  last_login_from_ip_address      :string
#  twitter_username                :string
#  asset_token                     :string
#  photo                           :string
#  photo_updated_at                :datetime
#

class User < ActiveRecord::Base
  include Authenticatable
  include Authorizable
  include Excludable
  include FileAttachable
  include PersistenceContextTrackable
  include User::Messaging

  has_many :social_links, class_name: 'User::SocialLink', dependent: :destroy
  has_many :providers, through: :user_providers

  store :preferences, accessors: [:preferred_locale]

  with_options foreign_key: :author_id, dependent: :nullify do |author|
    author.has_many :attachments
    author.has_many :images
    author.has_many :pages
    author.has_many :snippets
  end

  mount_uploader :photo, User::PhotoUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, email: true,
                    uniqueness: { case_sensitive: false }
  validates :preferred_locale,
            inclusion: { in: -> { I18n.available_locales.map(&:to_s) } },
            allow_blank: true

  after_initialize :generate_asset_token, unless: :asset_token?
  before_validation :sanitize_preferred_locale
  before_save :sanitize_email_address, if: :email?
  before_save :set_photo_updated_at, if: [:photo?, :photo_changed?]

  default_scope -> { order(:first_name, :last_name) }

  def self.find_by_name(name)
    find_by_name!(name) rescue nil
  end

  def self.find_by_name!(name)
    find_by!("(#{table_name}.first_name || ' ' || #{table_name}.last_name) = ?",
             name)
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  alias_method :name, :full_name

  def rfc5322
    if full_name.present?
      %("#{full_name}" <#{email}>)
    else
      email
    end
  end

  def to_liquid
    attributes.slice(*%w(first_name last_name email)).merge(
      'name' => full_name,
      'full_name' => full_name
    )
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def to_s
    full_name
  end

  private

  def generate_asset_token
    self.asset_token = SecureRandom.uuid
  end

  def sanitize_email_address
    self.email = email.downcase
  end

  def sanitize_preferred_locale
    self.preferred_locale = preferred_locale.to_s.downcase.presence
  end

  def set_photo_updated_at
    self.photo_updated_at = DateTime.now
  end
end

app/controllers/admin/attachments_controller.rb
class Admin::AttachmentsController < Admin::ApplicationController
  respond_to :html

  before_action :load_attachment, only: %i(show edit update destroy download convert_to_image)

  breadcrumbs do |b|
    b.append Attachment.model_name.human(count: 2), :admin_attachments
    b.append translate('breadcrumbs.upload', model: Attachment.model_name.human), :new_admin_attachment if action_name.in? %w(new create)
    b.append translate('breadcrumbs.edit', model: Attachment.model_name.human), [:edit, :admin, @attachment] if action_name.in? %w(edit update)
  end

  def index
    @attachments = Attachment.with_translations_for_current_locale.
                              select(Attachment.arel_table[Arel.star], Attachment::Translation.arel_table[:title]).
                              uniq.includes(:author)

    attachment_ids = Array(params[:id])
    if attachment_ids.any?
      if attachment_ids.one?
        return redirect_to safe_params.merge(action: :show)
      else
        @attachments = @attachments.where(id: attachment_id_or_ids)
      end
    else
      @attachments = @attachments.search(params[:query])
      @attachment_search = @attachments.ransack(params[:search])
      @attachment_search.sorts = 'translations_title asc' if @attachment_search.sorts.empty?
      @attachments = @attachment_search.result
    end

    @users = User.order(:first_name, :last_name)

    @attachments.where!(author_id: params[:author_id]) if params[:author_id].present?
    @attachments = @attachments.created(params[:period]) if params[:period].present?
    @attachments.where!(content_type: params[:content_type]) if params[:content_type].present?
    @attachments = @attachments.page(params[:page])

    respond_with :admin, @attachments do |format|
      format.json
    end
  end

  def upload
    @attachment = Attachment.new(attachment_upload_params)
    @attachment.author = current_user
    @attachment.save!

    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_with :admin, @attachment
  end

  def update
    @attachment.update(attachment_params)
    flash_for @attachment
    respond_with :admin, @attachment, location: :admin_attachments
  end

  def download
    send_file @attachment.asset.path, filename: @attachment.virtual_filename,
                                      content_type: @attachment.content_type,
                                      disposition: :attachment,
                                      x_sendfile: true
  end

  def destroy
    @attachment.destroy
    flash_for @attachment
    respond_with :admin, @attachment, location: :admin_attachments
  end

  def convert_to_image
    Attachment.transaction do
      @image = @attachment.to_image
      @image.save!
      @attachment.destroy!
    end
    respond_to do |format|
      format.html { redirect_to [:admin, @image] }
    end
  end

  # Batch Processing

  def batch_process
    if params.key? :destroy
      destroy_multiple
    else
      respond_to do |format|
        format.any { head :bad_request }
      end
    end
  end

  def destroy_multiple
    attachment_ids = Array(params[:attachment_ids]).map(&:to_i).reject(&:zero?)
    Attachment.accessible_by(current_ability).destroy_all(id: attachment_ids)
    flash_for Attachment, :destroyed, multiple: true
    location = request.referer || admin_attachments_path
    respond_to do |format|
      format.html { redirect_to location }
      format.js { redirect_via_turbolinks_to location }
    end
  end

  private :destroy_multiple # invoked through :batch_process

  private

  def attachment_params
    params.require(:attachment).permit(:title, :author_id, :description)
  end

  def attachment_upload_params
    params.require(:attachment).permit(:asset)
  end

  def load_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < DownloadsController
  before_action :load_attachment

  def show
    if @attachment.image?
      send_attachment @attachment, :inline
    else
      download
    end
  end

  def download
    send_attachment @attachment, :attachment
  end

  private

  def load_attachment
    @attachment = Attachment.find_by!(asset: params[:filename])
  end
end

app/views/admin/attachments/_attachment.html.haml
- present attachment, with: Admin::AttachmentPresenter do |attachment|
  = content_tag_for :tr, attachment do
    - if local_assigns.fetch(:checkbox, true)
      %td.checkbox-cell
        = check_box_tag 'attachment_ids[]', attachment.id, false, class: 'table-checkbox', id: nil
    %td
      = link_to attachment.title, attachment.show_path
      %br
      %span.text-muted.ignored= attachment.content_type
    %td= attachment.file_size
    %td= attachment.downloads_count
    - if local_assigns.fetch(:time, true)
      %td= attachment.updated_at
    - if local_assigns.fetch(:actions, true)
      %td.actions
        = attachment.action_buttons icon_only: true

app/views/admin/attachments/_form.html.haml
= simple_form_for [:admin, @attachment], html: { class: 'form-horizontal' } do |form|

  .form-group
    %label.control-label.col-sm-3
      = Attachment.human_attribute_name :original_filename
    .col-sm-9
      .form-control-static
        = link_to @attachment.original_filename, [:download, :admin, @attachment]

  = form.input :title
  = form.input :description, input_html: { class: 'caption-editor', rows: 6 }
  = form.association :author, as: :radio_buttons, wrapper: :horizontal_radio_and_checkboxes

  = form_actions do
    = form.button :button, type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate(@attachment.new_record? ? :create : :update, scope: 'helpers.submit', model: Page.model_name.human)
    = button_link_to translate('helpers.links.cancel'), :admin_attachments

app/views/admin/attachments/edit.html.haml
.row
  .col-sm-8.col-sm-offset-2
    = page_header
    = render 'form'

app/views/admin/attachments/index.html.haml
#attachment_upload_dropzone

  = page_header do
    = render 'search_component', search: @attachment_search, url: :admin_attachments

  .row

    .col-sm-3
      #filters.panel-group
        = panel link_to(prepend_icon(:user, Attachment.human_attribute_name(:author_id), fixed_width: true), '#author', data: { toggle: 'collapse' }), body: false do
          .list-group#author.panel-collapse.collapse.in
            = active_link_to 'Egal', params.except(:author_id), class: 'list-group-item', active: params[:author_id].nil?
            - @users.each do |user|
              = active_link_to params.except(:page).merge(author_id: user.to_param), class: 'list-group-item', active: user.id == params[:author_id].to_i do
                %span.avatar
                  %span.icon= user_thumbnail_image_tag user, size: 24, class: 'img-circle img-responsive'
                  %span.caption= user.name

        = panel link_to(prepend_icon(:calendar, Attachment.human_attribute_name(:created_at), fixed_width: true), '#period', data: { toggle: 'collapse' }), body: false do
          .list-group#period.panel-collapse.collapse{class: params[:period].nil? ? nil : 'in'}
            = active_link_to 'Egal', params.except(:period), class: 'list-group-item', active: params[:period].nil?
            - {'Heute' => 'today', 'Gestern' => 'yesterday', 'In dieser Woche' => 'week', 'In diesem Monat' => 'month'}.each do |caption, period|
              = active_link_to caption, params.except(:page).merge(period: period), class: 'list-group-item', active: period == params[:period]

    .col-sm-9
      = form_tag :batch_process_admin_attachments, method: :patch, remote: true do

        #toolbar.btn-toolbar
          .btn-group.only-js
            .btn.btn-success.btn-file
              = prepend_icon :upload, translate('helpers.links.upload', model: Attachment.model_name.human)
              = file_field_tag :attachment_upload, name: 'attachment[asset]', multiple: true, data: {bfi_disabled: true, url: upload_admin_attachments_path }
          .btn-group
            = button_tag name: 'destroy', class: 'btn btn-danger deactivatable-batch-control', data: { hotkey: 'del', confirm: translate('helpers.confirmations.destroy_selected', model: Attachment.model_name.human(count: 2)) } do
              = prepend_icon :trash, translate('helpers.links.destroy_selected'), outline: true
          .pull-right
            = paginate @attachments

        #attachments_empty_hint.well.text-center{class: @attachments.any? ? 'hidden' : nil}
          = translate('views.hints.empty', model: Attachment.model_name.human(count: 2))

        %table#attachments.table.table-hover{class: @attachments.empty? ? 'hidden' : nil}
          %thead
            %tr
              %th.checkbox-cell
                %input{type: 'checkbox', class: 'js-only table-checkbox-all', data: { toggle: 'tableCheckboxes' }}
              %th= sort_link @attachment_search, :translations_title
              %th= sort_link @attachment_search, :file_size
              %th= sort_link @attachment_search, :downloads_count
              %th= sort_link @attachment_search, :created_at
              %th.actions
          %tbody
            - @attachments.each do |attachment|
              = render 'attachment', attachment: attachment, checkbox: true