config/routes.rb
Rails.application.routes.draw do
  concern :autocompletable do
    collection do
      get :autocomplete
    end
  end

  concern :movable do
    member do
      patch :move_up
      patch :move_down
    end
  end

  concern :customizable do
    member do
      get :customize
      patch :customize, action: :apply_customization
    end
  end

  concern :taggable do
    member do
      patch :tag
      patch :untag
    end
  end

  concern :batch_processable do
    collection do
      patch :batch, action: :batch_process, as: :batch_process
    end
  end

  get 'sitemap.xml', to: 'sitemaps#index', as: :sitemaps, format: 'xml'
  get 'sitemap.:page.xml', to: 'sitemaps#show', as: :sitemap, format: 'xml'

  # Downloads
  scope 'files', constraints: { filename: /.*/ } do
    get 'images/download/:filename' => 'image/styles#download', as: :download_image_style
    get 'download/:filename' => 'attachments#download', as: :download_attachment
    get ':filename' => 'attachments#show', as: :attachment
  end

  scope '(:locale)', constraints: { locale: /[a-z]{2}/ } do
    scope constraints: Router::LocaleConstraint.new do
      namespace :admin do
        scope controller: :sessions do
          get :login, action: :new
          post :login, action: :create
          match :logout, action: :destroy, via: %i(get delete)
        end

        scope '(:translations)', constraints: { translations: /[a-z]{2}/ } do
          scope constraints: Router::LocaleConstraint.new(:translations) do
            get :search, controller: :search, action: :show

            namespace :editor do
              with_options only: [:show, :create, :update] do |r|
                r.resource :link
                r.resource :image
              end
            end

            namespace :stats do
              get 'disk_usage', to: 'disk_usage#index', as: :disk_usage

              scope :traffic, controller: :traffic do
                root action: :index, as: :traffic
                patch :reset, as: :reset_traffic
              end

              scope :downloads, controller: :downloads do
                root action: :index, as: :downloads
                scope '(:type)' do
                  get :total, as: :total_downloads
                  get ':year/:month', action: :month, as: :monthly_downloads, year: /[0-9]+/, month: /[0-9]+/
                  get ':year', action: :year, as: :yearly_downloads, year: /[0-9]+/
                end
                get :referers, as: :download_referers
              end

              scope :visits, controller: :visits do
                root action: :index, as: :visits
                get :total, as: :total_visits
                get ':year/:month', action: :month, as: :monthly_visits, year: /[0-9]+/, month: /[0-9]+/
                get ':year', action: :year, as: :yearly_visits, year: /[0-9]+/
              end
            end

            resource :account, except: %i(new create) do
              get :edit_password
              patch :update_password
              patch :update_preferences
            end

            resources :attachments, except: %i(new create show),
                                    concerns: :batch_processable do
              collection do
                match :upload, via: %i(post patch)
              end
              member do
                get :download
              end
              patch :convert_to_image, on: :member
            end

            resources :clients, only: %i(index edit update)

            resources :images, except: %i(new create), concerns: [:autocompletable,:customizable, :batch_processable, :taggable] do
              resources :styles, controller: :'image/styles', concerns: [:customizable, :movable, :batch_processable] do
                collection do
                  match :upload, via: %i(post patch)
                  delete :destroy_multiple
                end
              end
              resources :attachments, as: :attachments, controller: :'image/attachments', concerns: %i(movable batch_processable) do
                match :upload, on: :collection, via: %i(post patch)
              end
              resources :shop_links, controller: :'image/shop_links', except: %i(index show)
              collection do
                match :upload, via: %i(post patch)
                patch :associate_owner, action: :associate_owner, as: :associate_owner_with
                patch :associate_tags, action: :associate_tags, as: :associate_tags_with
              end
              member do
                get :pages
                get :download
                get :dimensions
                patch :convert_to_attachment
              end
            end

            resources :projects, concerns: [:autocompletable, :batch_processable, :taggable] do
              resources :images, controller: :'project/images', only: :destroy, concerns: [:movable, :batch_processable] do
                collection do
                  match :upload, via: %i(post patch)
                end
              end
              member do
                get :pages
                get :assign_images, as: :assign_images_to
                post :assign_images, action: :attach_images, as: :attach_images_to
              end
            end

            resources :providers, except: :show

            resources :messages, only: [:index, :show, :destroy] do
              collection do
                delete :destroy_multiple
              end
              member do
                patch :mark_read
                patch :mark_unread
              end
            end

            resources :pages, except: :new, concerns: [:autocompletable, :movable] do
              resources :children, controller: :pages, only: :new do
                get ':page_type', on: :new, action: :new, as: :typed
              end
              resources :regions, controller: :'page/regions', only: [:index, :edit, :update, :destroy] do
                patch :update_multiple, on: :collection
              end
              resource :image, controller: :'page/images', only: %i(new create)
              resource :contact_form, controller: :'page/contact_forms', only: [:edit, :update]
              resource :project, controller: :'page/projects', only: %i(new create)
              resource :redirection, controller: :'page/redirections', only: [:edit, :update]
              collection do
                get :tree
              end
              member do
                patch :move
                patch :publish
                patch :hide
                patch :enable_in_menu
                patch :disable_in_menu
                patch 'change_template/:template_id', action: :change_template, as: :change_template
              end
            end

            resources :redirections, only: [] do
              get :translation_fields, on: :collection
            end

            resources :tags, only: :index

            resources :templates, except: :new, concerns: :movable do
              resources :region_definitions, controller: :'template/region_definitions', except: [:index, :show], concerns: :movable
              get ':template_type', on: :new, action: :new, as: :typed
              collection do
                get 'types/:template_type', action: :index, as: :typed
                delete :destroy_multiple
              end
              member do
                delete 'destroy_region/:label', action: :destroy_region, as: :destroy_region
              end
            end

            resources :users do
              resources :social_links, controller: :'user/social_links', except: :show, concerns: :movable
              member do
                get :edit_password
                patch :update_password
              end
            end

            root to: redirect('/admin/pages')
          end
        end
      end

      # Legacy URLs that have changed permanently (HTTP 301)
      get 'image/:slug', to: redirect { |params, request|
        page = Page.images.find_by!('slug = ?', params[:slug])
        "/#{page.path}"
      }
      get 'category/:slug(/:page)', page: /\d/, to: redirect { |params, request|
                                      slug = params[:slug].split(',').first
                                      page = Page.contents.find_by!('slug = ?', slug)
                                      url = "/#{page.path}"
                                      page_index = params[:page].to_i
                                      url << "?page=#{page_index}" if page_index > 1
                                      url
                                    }

      get 'pic-:slug.:format', to: redirect { |params, request|
        page = Page.images.find_by!('slug = ?', params[:slug])
        page.image.asset.url(:public)
      }

      # Permalinks
      get ':id' => 'page/permalinks#show', as: :page_permalink, id: /[A-Z0-9]{6}/i
    end
  end
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id          :integer          not null, primary key
#  name        :string
#  country     :string(2)
#  website_url :string
#

class Client < ActiveRecord::Base
  include Searchable

  sanitizes :name, with: :squish
  sanitizes :country, with: :upcase

  acts_as_searchable_on :name

  has_many :projects, dependent: :nullify

  validates :name, presence: true, uniqueness: true
  validates :country, length: { is: 2 }, allow_blank: true
  validates :website_url, url: true, allow_blank: true

  def to_s
    name
  end
end

app/controllers/admin/page/projects_controller.rb
class Admin::Page::ProjectsController < Admin::Page::ApplicationController
  before_action :load_project, only: %i(edit update)

  def new
    @project_page_creation_form = Admin::ProjectPageCreationForm.new do |a|
      a.template = "Template::Project".constantize.default
      a.parent_page = @page
    end
    respond_to do |format|
      format.js
    end
  end

  def create
    @project_page_creation_form = Admin::ProjectPageCreationForm.new do |a|
      a.attributes = project_page_creation_form_params
      a.parent_page = @page
      a.submit
    end
    if @project_page_creation_form.errors.empty?
      @location = admin_page_path(@project_page_creation_form.parent_page)
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def load_project
    @project = @page.embeddable
  end

  def project_params
    params.require(:page_project).permit(:name, :description, :released_on, :client_name, :client_url)
  end

  def project_page_creation_form_params
    params.require(:project_page_creation_form).permit(:project_id_tokens, :template_id, :published)
  end
end

app/controllers/admin/project/images_controller.rb
class Admin::Project::ImagesController < Admin::ApplicationController
  respond_to :html, :js

  before_action :load_project
  before_action :load_project_image, only: %i(move_up move_down destroy)

  def upload
    Project::Image.transaction do
      image = ::Image.new(image_upload_params)
      image.author = current_user
      image.save!
      @project_image = @project.project_images.create!(image: image)
      @project_image.with_lock do
        @project_image.update_column(:position, @project.project_images.count)
      end
    end
    respond_to do |format|
      format.js { render :refresh_table }
    end
  end

  def move_up
    @project_image.with_lock do
      @project_image.move_higher
    end
    respond_with :admin, @project, @project_image, location: [:admin, @project] do |format|
      format.js { render :refresh_table }
    end
  end

  def move_down
    @project_image.with_lock do
      @project_image.move_lower
    end
    respond_with :admin, @project, @project_image, location: [:admin, @project] do |format|
      format.js { render :refresh_table }
    end
  end

  def destroy
    @project_image.destroy
    respond_with :admin, @project, @project_image, location: [:admin, @project] do |format|
      format.js { render :refresh_table }
    end
  end

  def batch_process
    if params.key? :destroy
      destroy_multiple
    else
      respond_to do |format|
        format.any { head :bad_request }
      end
    end
  end

  def destroy_multiple
    project_image_ids = Array(params[:project_image_ids]).map(&:to_i).reject(&:zero?)
    ::Project::Image.accessible_by(current_ability).destroy_all(id: project_image_ids)
    respond_to do |format|
      format.html { redirect_to [:admin, @project] }
      format.js { render :refresh_table }
    end
  end
  private :destroy_multiple

  private

  def load_project
    @project = ::Project.find(params[:project_id])
  end

  def load_project_image
    @project_image = @project.project_images.find_by!(id: params[:id])
  end

  def image_upload_params
    params.require(:image).permit(:asset)
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  respond_to :html

  before_action :load_project, only: %i(show edit update destroy assign_images
                                        attach_images pages)

  breadcrumbs do |b|
    b.append ::Project.model_name.human(count: 2), :admin_projects
    if action_name.in? %w(new create)
      b.append translate('breadcrumbs.new', model: ::Project.model_name.human),
               :new_admin_project
    end
    if @project
      b.append @project.title, [:admin, @project]
      if action_name.in? %w(edit update)
        b.append t('breadcrumbs.edit', model: ::Project.model_name.human),
                 [:edit, :admin, @project]
      end
    end
  end

  def index
    @clients = Client.order(:name)

    @projects = Project.with_translations_for_current_locale
                .eager_load(:client, :author)

    project_ids = Array(params[:id])
    if project_ids.any?
      return redirect_to safe_params.merge(action: :show) if project_ids.one?
      @projects.where!(id: project_ids)
    else
      @projects = @projects.search(params[:query])
      @project_search = @projects.ransack(params[:search])
      @project_search.sorts = 'created_at desc' if @project_search.sorts.empty?
      @projects = @project_search.result(distinct: true)
    end

    client_id = params[:client_id]
    @projects.where!(client_id: client_id) if client_id.present?

    @projects = @projects.page(params[:page])

    respond_with :admin, @projects do |format|
      format.json
    end
  end

  def autocomplete
    query = params[:query]
    if query.present?
      translated_title = Project::Translation.arel_table[:title]
      @projects = Project.search(query).includes(:client, :images)
                  .select(Project.arel_table[Arel.star], translated_title)
                  .order(translated_title.asc)
                  .with_translations_for_current_locale.uniq.limit(3)
    else
      @projects = Project.none
    end
    respond_to do |format|
      format.json
    end
  end

  def new
    @project = ::Project.new
    @project.author = current_user
    @project.released_in = Date.today.year
    respond_to do |format|
      format.js
    end
  end

  def create
    @project = ::Project.new(new_project_params)
    @project.author = current_user
    @project.save
    flash_for @project
    respond_to do |format|
      format.js
    end
  end

  def show
    @project_images = @project.project_images.includes(:image)
    respond_with :admin, @project do |format|
      format.json
    end
  end

  def edit
    respond_with :admin, @project
  end

  def update
    @project.update(project_params)
    flash_for @project
    respond_with :admin, @project, location: [:edit, :admin, @project]
  end

  def destroy
    @project.destroy
    flash_for @project
    respond_with :admin, @project
  end

  def assign_images
    @project_image_assignment_form = Admin::ProjectImageAssignmentForm.new
    @project_image_assignment_form.project = @project

    respond_to do |format|
      format.js
    end
  end

  def attach_images
    @project_image_assignment_form = Admin::ProjectImageAssignmentForm.new
    @project_image_assignment_form.attributes = project_image_assignment_params
    @project_image_assignment_form.project = @project
    @project_image_assignment_form.submit

    respond_to do |format|
      format.js
    end
  end

  def pages
    @pages = @project.pages.with_translations_for_current_locale

    respond_to do |format|
      format.js
    end
  end

  # Batch Processing

  def batch_process
    if params.key? :destroy
      destroy_multiple
    else
      respond_to do |format|
        format.any { head :bad_request }
      end
    end
  end

  def destroy_multiple
    project_ids = Array(params[:project_ids]).map(&:to_i).reject(&:zero?)
    ::Project.accessible_by(current_ability).destroy_all(id: project_ids)
    flash_for ::Project, :destroyed, multiple: true
    location = request.referer || admin_images_path

    respond_to do |format|
      format.html { redirect_to location }
      format.js { redirect_via_turbolinks_to location }
    end
  end
  private :destroy_multiple # invoked through :batch_process

  private

  def load_project
    @project = ::Project.find(params[:id])
  end

  def new_project_params
    params.require(:project).permit(:title, :project_type, :url,
                                    :client_name, :released_in)
  end

  def project_params
    params.require(:project).permit(
      :title, :project_type, :url, :client_name, :released_in, :description,
      :author_id, :propagate_changes_to_pages
    )
  end

  def project_image_assignment_params
    params.require(:project_image_assignment_form).permit(:image_id_tokens)
  end
end

app/views/admin/projects/_assign_images_form.html.haml
= simple_form_for @project_image_assignment_form, as: :project_image_assignment_form, url: [:assign_images_to, :admin, @project], remote: true, html: { class: 'form-horizontal' } do |form|

  .modal-body
    = form.input :image_id_tokens, as: :image_select, multiple: true

  .modal-footer
    = form.button :button, type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate('helpers.links.save')
    = button_tag translate('helpers.links.close'), type: 'button', class: 'btn btn-default', data: { dismiss: 'modal' }

app/views/admin/projects/_edit_form.html.haml
= simple_form_for [:admin, @project], html: { class: 'form-horizontal' } do |form|

  = form.input :title, input_html: { autofocus: true }
  = form.input :project_type
  = form.input :url
  = form.input :client_name, as: :client_select
  = form.input :released_in, collection: Date.today.year.downto(2005)
  = form.input :description, input_html: { class: 'caption-editor', rows: 10 }
  = form.association :author, as: :radio_buttons, wrapper: :horizontal_radio_and_checkboxes

  - if @project.pages.any?
    %fieldset
      %legend= Image.human_attribute_name :pages
      .fields
        = form.input :propagate_changes_to_pages, as: :boolean, wrapper: :horizontal_boolean, label: translate(@project.pages.one? ? :propagate_changes_to_page : :propagate_changes_to_n_pages, scope: 'activerecord.attributes.project', count: @project.pages.count)

  = form_actions do
    = form.button :button, type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate(@project.new_record? ? :create : :update, scope: 'helpers.submit', model: Project.model_name.human)
    = cancel_button [:admin, @project]

app/views/admin/projects/_form.html.haml
= simple_form_for [:admin, @project], html: { class: 'form-horizontal' } do |form|

  = form.input :title, input_html: { autofocus: true }
  = form.input :description, input_html: { class: 'simple-editor', rows: 7 }

  = form_actions do
    = form.button :button, type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate(@project.new_record? ? :create : :update, scope: 'helpers.submit', model: Project.model_name.human)
    = cancel_button [:admin, @project]

app/views/admin/projects/_new_form.html.haml
= simple_form_for [:admin, @project], remote: true, html: { class: 'form-horizontal' } do |form|

  .modal-body
    = form.input :title, input_html: { autofocus: true }
    = form.input :project_type
    = form.input :url
    = form.input :client_name, as: :client_select
    = form.input :released_in, collection: Date.today.year.downto(2005)

  .modal-footer
    = form.button :button, name: 'save', type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate('helpers.links.save'), scope: 'helpers.submit', model: Image.model_name.human
    = button_tag translate('helpers.links.close'), type: 'button', class: 'btn btn-default', data: { dismiss: 'modal' }

app/views/admin/projects/_project.html.haml
- present project, with: Admin::ProjectPresenter do |project|
  = content_tag_for :tr, project do
    - if local_assigns.fetch(:checkbox, true)
      %td.checkbox-cell
        = check_box_tag 'project_ids[]', project.id, false, class: 'table-checkbox', id: nil, data: { behavior: 'tableCheckbox' }
    %td
      = link_to project.title, [:admin, project]
      %br
      %span.text-muted.ignored= project.summary
    %td= project.client(true)
    %td= project.released_in
    %td= project.created_at
    - if local_assigns.fetch(:actions, true)
      %td.actions
        = project.action_buttons icon_only: true

app/views/admin/projects/assign_images.html.haml
- content_for :title, translate('breadcrumbs.assign', model: Project::Image.model_name.human(count: 2))

- content_for :content do
  = render 'assign_images_form'

app/views/admin/projects/edit.html.haml
.row
  .col-sm-8.col-sm-offset-2
    = page_header
    = render 'edit_form'

app/views/admin/projects/index.html.haml
= page_header do
  = render 'search_component', search: @project_search, url: :admin_projects

.row

  .col-sm-3
    #filters.panel-group
      = panel link_to(prepend_icon(:users, Project.human_attribute_name(:client), fixed_width: true), '#client', data: { toggle: 'collapse' }), body: false do
        #client.list-group.panel-collapse.collapse.in
          = active_link_to 'Egal', params.except(:client_id), class: 'list-group-item', active: params[:client_id].nil?
          - @clients.each do |client|
            = active_link_to client.name, params.except(:page).merge(client_id: client.to_param), class: 'list-group-item', active: client.id == params[:client_id].to_i

  .col-sm-9
    = form_tag :batch_process_admin_projects, method: :patch, remote: true do

      #toolbar.btn-toolbar
        .btn-group.only-js
          = create_button_link_for Project, namespace: :admin, icon: :plus, caption: translate('helpers.links.new', model: Project.model_name.human), remote: true
        .btn-group
          = button_tag name: 'destroy', class: 'btn btn-danger deactivatable-batch-control', data: { hotkey: 'del', confirm: translate('helpers.confirmations.destroy_selected', model: Image.model_name.human(count: 2)) } do
            = prepend_icon :trash, translate('helpers.links.destroy_selected'), outline: true
        .pull-right
          = paginate @projects

      #projects_empty_hint.well.text-center{class: @projects.any? ? 'hidden' : nil}
        = translate('views.hints.empty', model: Project.model_name.human(count: 2))

      %table#projects.table.table-hover{class: @projects.empty? ? 'hidden' : nil}
        %thead
          %tr
            %th.checkbox-cell
              %input{type: 'checkbox', class: 'js-only table-checkbox-all', data: { toggle: 'tableCheckboxes' }}
            %th= sort_link @project_search, :translations_title
            %th= sort_link @project_search, :client_name, Project.human_attribute_name(:client_name)
            %th= sort_link @project_search, :released_in, Project.human_attribute_name(:released_in), default_order: :desc
            %th= sort_link @project_search, :created_at, Project.human_attribute_name(:created_at), default_order: :desc
            %th.actions
        %tbody
          - @projects.each do |project|
            = render project

app/views/admin/projects/new.html.haml
- content_for :title, translate('breadcrumbs.new', model: Project.model_name.human)

- content_for :content do
  = render 'new_form'

app/views/admin/projects/pages.html.haml
- content_for :title do
  = Page::Project.model_name.human(count: 2)
  .badge= @pages.count

- content_for :content do
  .modal-body
    - if @pages.any?
      %ul.list-unstyled.list-wide
        - @pages.each do |page|
          = content_tag_for :li, page do
            = link_to page.title, [:admin, page]
            .text-muted
              = page.path
    - else
      = translate 'views.hints.empty', model: Page::Project.model_name.human(count: 2)

app/views/admin/projects/show.html.haml
- present @project, with: Admin::ProjectPresenter do |project|

  = page_header do
    .btn-toolbar
      .btn-group.pull-right
        = button_link_to [:edit, :admin, project], data: { toggle: 'dropdown' }, class: 'dropdown-toggle' do
          = prepend_icon :cog, translate('helpers.links.settings'), fixed_width: true, caption_html: { class: 'sr-only' }
        %ul.dropdown-menu{role: 'menu', aria_labelledby: 'dLabel'}
          %li= link_to prepend_icon(:pencil, translate('helpers.links.edit'), fixed_width: true), [:edit, :admin, project]
          %li= link_to prepend_icon(:trash, translate('helpers.links.destroy'), outline: true, fixed_width: true), [:admin, project], method: :delete, data: { confirm: translate('helpers.confirmations.destroy', model: Project.model_name.human) }

  .row
    .col-lg-8

      - if project.description.present?
        = panel Project.human_attribute_name(:description) do
          = liquify project.description, with: project

      #project_image_upload_dropzone
        = form_tag batch_process_admin_project_images_path(@project), method: :patch, remote: true do

          .panel.panel-default
            .panel-heading
              %h4.panel-title= prepend_icon :picture, Project::Image.model_name.human(count: 2), outline: true, fixed_width: true

            = render 'admin/project/images/table'

            .panel-footer.clearfix
              .btn-toolbar.pull-left
                .btn-group
                  = button_tag name: 'destroy', class: 'btn btn-danger deactivatable-batch-control', data: { hotkey: 'del', confirm: translate('helpers.confirmations.destroy_selected', model: Image::Style.model_name.human(count: 2)) } do
                    = prepend_icon :trash, translate('helpers.links.destroy_selected'), outline: true
              .btn-toolbar.pull-right
                .btn-group.only-js
                  .btn.btn-success.btn-file
                    = prepend_icon :upload, translate('helpers.links.upload', model: Image.model_name.human(count: 2))
                    = file_field_tag :image_upload, name: 'image[asset]', multiple: true, data: { url: upload_admin_project_images_path(@project), bfi_disabled: true }
                .btn-group
                  = button_link_to [:assign_images_to, :admin, @project], remote: true do
                    = prepend_icon :mail_forward, translate('helpers.links.assign', model: Image.model_name.human(count: 2))

    .col-lg-4
      - if project.url.present?
        .panel.panel-invisible
          = button_link_to project.url, type: :primary, size: :lg, block: true, target: '_blank', data: { no_turbolink: true } do
            = prepend_icon :external_link, translate('helpers.model_links.view', model: Project.model_name.human), fixed_width: true

      - if project.author.present?
        = panel do
          .row
            .col-sm-3
              = project.author.thumbnail(true, class: 'img-circle img-responsive')
            .col-sm-9
              = project.author.name(true)
              .text-muted= project.updated_at

      = panel prepend_icon(:info, translate('views.admin.projects.headlines.details'), fixed_width: true) do
        %dl.dl-horizontal
          = project.list_item :project_type
          = project.list_item :client, true
          = project.list_item :released_in
          = project.list_item :pages_count, true