config/routes.rb
Rails.application.routes.draw do
  concern :autocompletable do
    collection do
      get :autocomplete
    end
  end

  concern :movable do
    member do
      patch :move_up
      patch :move_down
    end
  end

  concern :customizable do
    member do
      get :customize
      patch :customize, action: :apply_customization
    end
  end

  concern :taggable do
    member do
      patch :tag
      patch :untag
    end
  end

  concern :batch_processable do
    collection do
      patch :batch, action: :batch_process, as: :batch_process
    end
  end

  get 'sitemap.xml', to: 'sitemaps#index', as: :sitemaps, format: 'xml'
  get 'sitemap.:page.xml', to: 'sitemaps#show', as: :sitemap, format: 'xml'

  # Downloads
  scope 'files', constraints: { filename: /.*/ } do
    get 'images/download/:filename' => 'image/styles#download', as: :download_image_style
    get 'download/:filename' => 'attachments#download', as: :download_attachment
    get ':filename' => 'attachments#show', as: :attachment
  end

  scope '(:locale)', constraints: { locale: /[a-z]{2}/ } do
    scope constraints: Router::LocaleConstraint.new do
      namespace :admin do
        scope controller: :sessions do
          get :login, action: :new
          post :login, action: :create
          match :logout, action: :destroy, via: %i(get delete)
        end

        scope '(:translations)', constraints: { translations: /[a-z]{2}/ } do
          scope constraints: Router::LocaleConstraint.new(:translations) do
            get :search, controller: :search, action: :show

            namespace :editor do
              with_options only: [:show, :create, :update] do |r|
                r.resource :link
                r.resource :image
              end
            end

            namespace :stats do
              get 'disk_usage', to: 'disk_usage#index', as: :disk_usage

              scope :traffic, controller: :traffic do
                root action: :index, as: :traffic
                patch :reset, as: :reset_traffic
              end

              scope :downloads, controller: :downloads do
                root action: :index, as: :downloads
                scope '(:type)' do
                  get :total, as: :total_downloads
                  get ':year/:month', action: :month, as: :monthly_downloads, year: /[0-9]+/, month: /[0-9]+/
                  get ':year', action: :year, as: :yearly_downloads, year: /[0-9]+/
                end
                get :referers, as: :download_referers
              end

              scope :visits, controller: :visits do
                root action: :index, as: :visits
                get :total, as: :total_visits
                get ':year/:month', action: :month, as: :monthly_visits, year: /[0-9]+/, month: /[0-9]+/
                get ':year', action: :year, as: :yearly_visits, year: /[0-9]+/
              end
            end

            resource :account, except: %i(new create) do
              get :edit_password
              patch :update_password
              patch :update_preferences
            end

            resources :attachments, except: %i(new create show),
                                    concerns: :batch_processable do
              collection do
                match :upload, via: %i(post patch)
              end
              member do
                get :download
              end
              patch :convert_to_image, on: :member
            end

            resources :clients, only: %i(index edit update)

            resources :images, except: %i(new create), concerns: [:autocompletable,:customizable, :batch_processable, :taggable] do
              resources :styles, controller: :'image/styles', concerns: [:customizable, :movable, :batch_processable] do
                collection do
                  match :upload, via: %i(post patch)
                  delete :destroy_multiple
                end
              end
              resources :attachments, as: :attachments, controller: :'image/attachments', concerns: %i(movable batch_processable) do
                match :upload, on: :collection, via: %i(post patch)
              end
              resources :shop_links, controller: :'image/shop_links', except: %i(index show)
              collection do
                match :upload, via: %i(post patch)
                patch :associate_owner, action: :associate_owner, as: :associate_owner_with
                patch :associate_tags, action: :associate_tags, as: :associate_tags_with
              end
              member do
                get :pages
                get :download
                get :dimensions
                patch :convert_to_attachment
              end
            end

            resources :projects, concerns: [:autocompletable, :batch_processable, :taggable] do
              resources :images, controller: :'project/images', only: :destroy, concerns: [:movable, :batch_processable] do
                collection do
                  match :upload, via: %i(post patch)
                end
              end
              member do
                get :pages
                get :assign_images, as: :assign_images_to
                post :assign_images, action: :attach_images, as: :attach_images_to
              end
            end

            resources :providers, except: :show

            resources :messages, only: [:index, :show, :destroy] do
              collection do
                delete :destroy_multiple
              end
              member do
                patch :mark_read
                patch :mark_unread
              end
            end

            resources :pages, except: :new, concerns: [:autocompletable, :movable] do
              resources :children, controller: :pages, only: :new do
                get ':page_type', on: :new, action: :new, as: :typed
              end
              resources :regions, controller: :'page/regions', only: [:index, :edit, :update, :destroy] do
                patch :update_multiple, on: :collection
              end
              resource :image, controller: :'page/images', only: %i(new create)
              resource :contact_form, controller: :'page/contact_forms', only: [:edit, :update]
              resource :project, controller: :'page/projects', only: %i(new create)
              resource :redirection, controller: :'page/redirections', only: [:edit, :update]
              collection do
                get :tree
              end
              member do
                patch :move
                patch :publish
                patch :hide
                patch :enable_in_menu
                patch :disable_in_menu
                patch 'change_template/:template_id', action: :change_template, as: :change_template
              end
            end

            resources :redirections, only: [] do
              get :translation_fields, on: :collection
            end

            resources :tags, only: :index

            resources :templates, except: :new, concerns: :movable do
              resources :region_definitions, controller: :'template/region_definitions', except: [:index, :show], concerns: :movable
              get ':template_type', on: :new, action: :new, as: :typed
              collection do
                get 'types/:template_type', action: :index, as: :typed
                delete :destroy_multiple
              end
              member do
                delete 'destroy_region/:label', action: :destroy_region, as: :destroy_region
              end
            end

            resources :users do
              resources :social_links, controller: :'user/social_links', except: :show, concerns: :movable
              member do
                get :edit_password
                patch :update_password
              end
            end

            root to: redirect('/admin/pages')
          end
        end
      end

      # Legacy URLs that have changed permanently (HTTP 301)
      get 'image/:slug', to: redirect { |params, request|
        page = Page.images.find_by!('slug = ?', params[:slug])
        "/#{page.path}"
      }
      get 'category/:slug(/:page)', page: /\d/, to: redirect { |params, request|
                                      slug = params[:slug].split(',').first
                                      page = Page.contents.find_by!('slug = ?', slug)
                                      url = "/#{page.path}"
                                      page_index = params[:page].to_i
                                      url << "?page=#{page_index}" if page_index > 1
                                      url
                                    }

      get 'pic-:slug.:format', to: redirect { |params, request|
        page = Page.images.find_by!('slug = ?', params[:slug])
        page.image.asset.url(:public)
      }

      # Permalinks
      get ':id' => 'page/permalinks#show', as: :page_permalink, id: /[A-Z0-9]{6}/i
    end
  end
end

app/models/concerns/image/attachable.rb
class Image < ActiveRecord::Base
  module Attachable
    extend ActiveSupport::Concern

    MIME_TYPES = [Mime::JPEG, Mime::GIF, Mime::PNG].freeze

    module ClassMethods
      def has_image(uploader_class = nil)
        include FileAttachable
        has_attachment(uploader_class)
        include Extensions
      end
    end

    module Extensions
      extend ActiveSupport::Concern

      included do
        store :customization_options

        validates :content_type, presence: true,
                                 inclusion: { in: ->(attachable) { attachable.class.permitted_content_types }, allow_blank: true }

        with_options if: [:asset?, :asset_changed?] do |opts|
          opts.before_save :set_original_geometry
          opts.before_save :set_geometry
        end
      end

      module ClassMethods
        def permitted_content_types
          permitted_mime_types.map(&:to_s).freeze
        end

        def permitted_mime_types
          MIME_TYPES
        end
      end

      def recreate_assets!
        asset.recreate_versions!
        set_content_type
        set_file_size
        set_geometry
        set_asset_updated_at
        save!
      end

      def format
        mime_type.to_sym
      end

      def mime_type
        self.class.permitted_mime_types.find do |content_type|
          content_type == self.content_type
        end
      end

      # Dimensions

      def aspect_ratio
        Rational(width, height)
      end

      protected

      def set_content_type
        self.content_type = asset.custom.file.content_type
      end

      def set_file_size
        self.file_size = asset.custom.file.size
      end

      def set_geometry
        img = Magick::Image.read(asset.custom.path).first
        self.width = img.columns
        self.height = img.rows
      end

      def set_original_geometry
        img = Magick::Image.read(asset.path).first
        self.original_width = img.columns
        self.original_height = img.rows
      end
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  first_name                      :string
#  last_name                       :string
#  created_at                      :datetime
#  updated_at                      :datetime
#  preferences                     :text
#  email                           :string           not null
#  crypted_password                :string           not null
#  salt                            :string           not null
#  remember_me_token               :string
#  remember_me_token_expires_at    :datetime
#  reset_password_token            :string
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  failed_logins_count             :integer          default(0)
#  lock_expires_at                 :datetime
#  unlock_token                    :string
#  last_login_at                   :datetime
#  last_logout_at                  :datetime
#  last_activity_at                :datetime
#  last_login_from_ip_address      :string
#  twitter_username                :string
#  asset_token                     :string
#  photo                           :string
#  photo_updated_at                :datetime
#

class User < ActiveRecord::Base
  include Authenticatable
  include Authorizable
  include Excludable
  include FileAttachable
  include PersistenceContextTrackable
  include User::Messaging

  has_many :social_links, class_name: 'User::SocialLink', dependent: :destroy
  has_many :providers, through: :user_providers

  store :preferences, accessors: [:preferred_locale]

  with_options foreign_key: :author_id, dependent: :nullify do |author|
    author.has_many :attachments
    author.has_many :images
    author.has_many :pages
    author.has_many :snippets
  end

  mount_uploader :photo, User::PhotoUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, email: true,
                    uniqueness: { case_sensitive: false }
  validates :preferred_locale,
            inclusion: { in: -> { I18n.available_locales.map(&:to_s) } },
            allow_blank: true

  after_initialize :generate_asset_token, unless: :asset_token?
  before_validation :sanitize_preferred_locale
  before_save :sanitize_email_address, if: :email?
  before_save :set_photo_updated_at, if: [:photo?, :photo_changed?]

  default_scope -> { order(:first_name, :last_name) }

  def self.find_by_name(name)
    find_by_name!(name) rescue nil
  end

  def self.find_by_name!(name)
    find_by!("(#{table_name}.first_name || ' ' || #{table_name}.last_name) = ?",
             name)
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  alias_method :name, :full_name

  def rfc5322
    if full_name.present?
      %("#{full_name}" <#{email}>)
    else
      email
    end
  end

  def to_liquid
    attributes.slice(*%w(first_name last_name email)).merge(
      'name' => full_name,
      'full_name' => full_name
    )
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def to_s
    full_name
  end

  private

  def generate_asset_token
    self.asset_token = SecureRandom.uuid
  end

  def sanitize_email_address
    self.email = email.downcase
  end

  def sanitize_preferred_locale
    self.preferred_locale = preferred_locale.to_s.downcase.presence
  end

  def set_photo_updated_at
    self.photo_updated_at = DateTime.now
  end
end

app/controllers/admin/editor/images_controller.rb
class Admin::Editor::ImagesController < Admin::Editor::ApplicationController
  editor_actions_for :image, params: [:external, :url, :image_id, :original_style, :style_id, :alternative_text, :width, :height, :alignment]
end

app/controllers/admin/image/attachments_controller.rb
module Admin
  module Image
    class AttachmentsController < Admin::ApplicationController
      before_action :load_image
      before_action :load_image_attachment, only: %i(move_up move_down destroy)

      def new
        @attachment_assignment_form = Admin::Image::AttachmentAssignmentForm.new
        @attachment_assignment_form.image = @image

        respond_to :js
      end

      def create
        @attachment_assignment_form = Admin::Image::AttachmentAssignmentForm.new
        @attachment_assignment_form.image = @image
        @attachment_assignment_form.attributes =
          image_attachment_assignment_params
        @attachment_assignment_form.submit

        respond_to :js
      end

      def upload
        @attachment_upload_form = Admin::Image::AttachmentUploadForm.new
        @attachment_upload_form.image = @image
        @attachment_upload_form.attributes = image_attachment_upload_params
        @attachment_upload_form.submit

        respond_to do |format|
          format.js { render :refresh }
        end
      end

      def destroy
        @image_attachment.destroy

        respond_to do |format|
          format.js { render :refresh }
        end
      end

      # Position Change

      def move_up
        @image_attachment.with_lock do
          @image_attachment.move_higher
        end

        respond_to do |format|
          format.js { render :refresh }
        end
      end

      def move_down
        @image_attachment.with_lock do
          @image_attachment.move_lower
        end

        respond_to do |format|
          format.js { render :refresh }
        end
      end

      # Batch Processing

      def batch_process
        if params.key? :destroy
          destroy_multiple
        else
          respond_to do |format|
            format.any { head :unprocessable_entity }
          end
        end
      end

      private

      def load_image
        @image = ::Image.find(params[:image_id])
      end

      def load_image_attachment
        @image_attachment = @image.image_attachments.find(params[:id])
      end

      def image_attachment_assignment_params
        params.require(:image_attachment_assignment).permit(:attachment_ids)
      end

      def image_attachment_upload_params
        params.require(:image_attachment_upload).permit(:asset)
      end

      def destroy_multiple
        ids = Array(params[:image_attachment_ids]).map(&:to_i).reject(&:zero?)
        ::Image::Attachment.accessible_by(current_ability).destroy_all(id: ids)

        flash_for ::Image::Attachment, :destroyed, multiple: true
        location = request.referer || [:admin, @image]

        respond_to do |format|
          format.html { redirect_to location }
          format.js { redirect_via_turbolinks_to location }
        end
      end
    end
  end
end

app/views/admin/images/_assign_owner_form.html.haml
= simple_form_for @image_owner_assignment_form, as: :image_owner_assignment, url: :associate_owner_with_admin_images, remote: true, method: :patch, html: { class: 'form-horizontal' } do |form|
  .modal-body
    - form.object.image_ids.each do |image_id|
      = form.input_field :image_ids, value: image_id, as: :hidden, multiple: true
    = form.input :author_id, collection: User.all, as: :radio_buttons, wrapper: :horizontal_radio_and_checkboxes

  .modal-footer
    = form.button :button, name: 'save', type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate('helpers.links.save'), scope: 'helpers.submit', model: Image.model_name.human
    = button_tag translate('helpers.links.close'), type: 'button', class: 'btn btn-default', data: { dismiss: 'modal' }

app/views/admin/images/_customize_form.html.haml
= simple_form_for [:admin, @image], url: [:customize, :admin, @image], remote: true, html: { class: 'form-horizontal' } do |form|
  #image_manipulator.modal-body
    .row
      .col-sm-12
        .img-editable.img-rounded.text-center
          = image_tag @image.asset.url, id: 'image_asset', class: 'img-croppable img-responsive', alt: @image.title, data: { behavior: 'croppable', original_width: @image.original_width, original_height: @image.original_height }, width: '867'

    %br

    .row
      .col-sm-8
        .panel.panel-default.crop-panel
          .panel-heading
            %span.panel-title
              %label.checkbox
                = form.check_box :cropped, class: 'js-only', data: { toggle: 'crop' }
                = prepend_icon(:crop, translate('views.admin.images.headlines.crop'), fixed_width: true)
          .panel-body
            .row
              .col-sm-3
                = form.input_field :crop_x, as: :integer, placeholder: Image.human_attribute_name(:crop_x), class: 'form-control crop-x', min: 0, max: @image.width, data: { control: 'cropX' }
              .col-sm-3
                = form.input_field :crop_y, as: :integer, placeholder: Image.human_attribute_name(:crop_y), class: 'form-control crop-y', min: 0, max: @image.height, data: { control: 'cropY' }
              .col-sm-3
                = form.input_field :crop_width, as: :integer, placeholder: Image.human_attribute_name(:crop_width), class: 'form-control crop-width', min: 1, max: @image.width, data: { control: 'cropWidth' }
              .col-sm-3
                = form.input_field :crop_height, as: :integer, placeholder: Image.human_attribute_name(:crop_height), class: 'form-control crop-height', min: 1, max: @image.height, data: { control: 'cropHeight' }

      .col-sm-4
        .panel.panel-default.resize-panel
          .panel-heading
            %span.panel-title
              %label.checkbox
                = form.check_box :resized, class: 'js-only', data: { toggle: 'resize' }
                = prepend_icon(:arrows, translate('views.admin.images.headlines.resize'), fixed_width: true)
          .panel-body
            .row
              .col-sm-6
                = form.input_field :resize_width, as: :integer, placeholder: Image.human_attribute_name(:resize_width), class: 'form-control resize-width', min: 1, data: { control: 'resizeWidth' }
              .col-sm-6
                = form.input_field :resize_height, as: :integer, placeholder: Image.human_attribute_name(:resize_height), class: 'form-control resize-height', min: 1, data: { control: 'resizeHeight' }
            .row
              .col-sm-12
                .checkbox
                  %label
                    %input{type: 'checkbox', checked: true, class: 'resize-aspect-ratio', data: { control: 'preserveResizeAspectRatio' }}
                    = Image::Style.human_attribute_name(:preserve_aspect_ratio)


  .modal-footer
    = form.button :button, type: 'submit', class: 'btn-primary' do
      = prepend_icon :save, translate('helpers.links.save')
    = button_tag translate('helpers.links.close'), type: 'button', class: 'btn btn-default', data: { dismiss: 'modal' }

app/views/admin/images/_image.html.haml
- present image, with: Admin::ImagePresenter do |image|
  = content_tag_for :tr, image do
    - if local_assigns.fetch(:checkbox, true)
      %td.checkbox-cell
        = check_box_tag 'image_ids[]', image.id, false, class: 'table-checkbox', id: nil, data: { behavior: 'tableCheckbox' }
    %td.thumbnail-cell
      = link_to [:admin, image] do
        = image_tag attached_asset_path(image, :thumbnail), class: 'img-circle', alt: image.title, width: 45, height: 45
    %td
      = link_to image.title, [:admin, image]
      %br
      /= image.tag_list size: :sm
      %span.text-muted.ignored= image.summary
    %td
      %span.ignored= image.created_at
    - if local_assigns.fetch(:actions, true)
      %td.actions
        = image.action_buttons icon_only: true

app/views/admin/images/_table.html.haml
- images ||= @images
- actions = true if actions.nil?
- checkboxes = false if checkboxes.nil?

- if checkboxes
  = hidden_field_tag 'image_ids[]', '', id: nil

- if current_user.preferences[:image_view_mode] == 'tiles'

  - images.each_slice(4) do |sliced_images|
    .row
      - sliced_images.each_with_index do |image, index|
        - present image, with: Admin::ImagePresenter do |image|
          .col-sm-3
            = link_to [:admin, image], class: 'thumbnail', data: { toggle: 'popover', trigger: 'hover', title: image.title, content: image.preview_html, html: true, container: 'body', placement: index == 3 ? 'left' : 'right' } do
              = image_tag image.asset.url(:thumbnail), alt: image.title

- else

  %table.table.table-hover
    %thead
      %tr
        - if checkboxes
          %th.checkbox-cell
            %input{type: 'checkbox', class: 'js-only table-checkbox-all'}
        %th.thumbnail-cell
        %th.hidden-xs= sort_link_for images, :title
        %th.hidden-xs= Image.human_attribute_name :content_type
        /%th= Image.human_attribute_name :dimensions
        %th.visible-lg= sort_link_for images, :author
        - if actions
          %th.actions
    %tbody
      - images.each do |image|
        - present image, with: Admin::ImagePresenter do |image|
          = content_tag_for :tr, image do
            - if checkboxes
              %td.checkbox-cell
                = check_box_tag 'image_ids[]', image.id, false, class: 'table-checkbox', id: nil
            %td.thumbnail-cell
              = link_to image.thumbnail(size: 45), [:admin, image]
            %td= link_to image.title, [:admin, image]
            %td.hidden-xs= image.content_type
            %td.visible-lg= image.author
            - if actions
              %td.actions
                = image.action_buttons size: :xs, icon_only: true

app/views/admin/images/assign_owner.html.haml
- content_for :title, translate('helpers.links.assign_owner', model: Image.model_name.human)

- content_for :content do
  = render 'assign_owner_form'

app/views/admin/images/assign_tags.html.haml
- content_for :title, translate('helpers.links.assign_tags', model: Image.model_name.human)

- content_for :content do
  = render 'assign_tags_form'

app/views/admin/images/show.html.haml
- present @image, with: Admin::ImagePresenter do |image|

  = page_header do
    .btn-toolbar
      .btn-group.pull-right
        = button_link_to [:edit, :admin, image], data: { toggle: 'dropdown' }, class: 'dropdown-toggle' do
          = prepend_icon :cog, translate('helpers.links.settings'), fixed_width: true, caption_html: { class: 'sr-only' }
        %ul.dropdown-menu{role: 'menu', aria_labelledby: 'dLabel'}
          %li= link_to prepend_icon(:pencil, translate('helpers.links.edit'), fixed_width: true), [:edit, :admin, image]
          %li= link_to prepend_icon(:crop, translate('helpers.links.edit_image'), fixed_width: true), [:customize, :admin, image], remote: true
          %li.divider
          %li= link_to prepend_icon(:folder_open, translate('helpers.links.convert_to', model: Attachment.model_name.human), outline: true, fixed_width: true), [:convert_to_attachment, :admin, image], method: :patch, data: { confirm: translate('helpers.confirmations.convert', model: Image.model_name.human, other_model: Attachment.model_name.human(count: 2)) }
          %li.divider
          %li= link_to prepend_icon(:trash, translate('helpers.links.destroy'), outline: true, fixed_width: true), [:admin, image], method: :delete, data: { confirm: translate('helpers.confirmations.destroy', model: Image.model_name.human) }

  - if @tags.any?
    #tags.panel.panel-invisible
      %ul.tags
        - @tags.each do |tag|
          %li
            .tag.tag-interactive
              = link_to admin_images_path(tag: tag.label) do
                = tag.label
              = link_to untag_admin_image_path(@image, tag: tag.label), class: 'pull-right btn-tag', method: :patch, remote: true, data: { confirm: translate('helpers.confirmations.destroy', model: Tag.model_name.human) } do
                = prepend_icon :times, translate('helpers.links.remove'), caption_html: { class: 'sr-only' }

  .row
    .col-lg-8
      .panel.panel-invisible
        = link_to attached_asset_path(image, :public), target: '_blank' do
          = image_tag attached_asset_path(image, :custom), class: 'img-responsive img-editable img-rounded center-block', alt: image.title

      / Styles
      #image_style_upload_dropzone
        = form_tag batch_process_admin_image_styles_path(@image), method: :patch, remote: true do
          .panel.panel-default
            .panel-heading
              %h4.panel-title= prepend_icon :picture, Image::Style.model_name.human(count: 2), outline: true, fixed_width: true
            = render 'admin/image/styles/table'
            .panel-footer.clearfix
              .btn-toolbar.pull-left
                .btn-group
                  = button_tag name: 'destroy', class: 'btn btn-danger deactivatable-batch-control', data: { hotkey: 'del', confirm: translate('helpers.confirmations.destroy_selected', model: Image::Style.model_name.human(count: 2)) } do
                    = prepend_icon :trash, translate('helpers.links.destroy_selected'), outline: true
              .btn-toolbar.pull-right
                .btn-group.only-js
                  .btn.btn-success.btn-file
                    = prepend_icon :upload, translate('helpers.links.upload', model: Image::Style.model_name.human)
                    = file_field_tag :image_style_upload, name: 'image_style[asset]', multiple: true, data: { url: upload_admin_image_styles_path(@image), bfi_disabled: true }
                .btn-group
                  = button_link_to new_admin_image_style_path(@image), remote: true do
                    = prepend_icon :plus, translate('helpers.links.new', model: Image::Style.model_name.human)

      / Downloads
      #image_attachment_upload_dropzone
        = form_tag batch_process_admin_image_attachments_path(@image), method: :patch, remote: true do
          .panel.panel-default
            .panel-heading
              %h4.panel-title= prepend_icon :paperclip, Image::Attachment.model_name.human(count: 2), fixed_width: true
            #image_attachments.panel-table-container
              = render 'admin/image/attachments/table'
            .panel-footer.clearfix
              .btn-toolbar.pull-left
                .btn-group
                  = button_tag name: 'destroy', class: 'btn btn-danger deactivatable-batch-control', data: { hotkey: 'del', confirm: translate('helpers.confirmations.destroy_selected', model: Image::Attachment.model_name.human(count: 2)) } do
                    = prepend_icon :trash, translate('helpers.links.destroy_selected'), outline: true
              .btn-toolbar.pull-right
                .btn-group.only-js
                  .btn.btn-success.btn-file
                    = prepend_icon :upload, translate('helpers.links.upload', model: Image::Attachment.model_name.human)
                    = file_field_tag :image_attachment_upload, name: 'image_attachment_upload[asset]', multiple: true, data: { url: upload_admin_image_attachments_path(@image), bfi_disabled: true }
                .btn-group
                  = button_link_to new_admin_image_attachment_path(@image), remote: true do
                    = prepend_icon :plus, translate('helpers.links.assign', model: Attachment.model_name.human)

    .col-lg-4
      .panel.panel-invisible
        = button_link_to [:download, :admin, image], type: :primary, size: :lg, block: true, data: { no_turbolink: true } do
          = prepend_icon :download, translate('helpers.links.download'), fixed_width: true
          %small (#{image.file_size})

      / Short Info
      - if image.author.present?
        = panel do
          .row
            .col-sm-3
              = image.author.thumbnail(true, class: 'img-circle img-responsive')
            .col-sm-9
              = image.author.name(true)
              .text-muted= image.updated_at
              .text-muted= image.styles_count

      - if image.description.present?
        = panel do
          = liquify image.description, with: image

      / Details
      = panel prepend_icon(:info, translate('views.admin.images.headlines.details'), fixed_width: true) do
        %dl.dl-horizontal#properties
          = image.list_item :content_type
          = image.list_item :file_size, true
          = image.list_item :dimensions, true
          = image.list_item :pixels_count
          = image.list_item :artist if image.artist.present?
          = image.list_item :camera if image.camera.present?
          = image.list_item :software if image.software.present?
          = image.list_item :taken_at if image.taken_at.present?
          = image.list_item :pages_count, true

      / Shops
      .panel.panel-default
        .panel-heading
          %h4.panel-title
            = prepend_icon :dollar, Image::ShopLink.model_name.human(count: 2), fixed_width: true

        = render 'admin/image/shop_links/table'

        - if can? :create, Image::ShopLink
          .panel-footer.clearfix
            = button_link_to [:new, :admin, @image, :shop_link], type: :success, block: true, remote: true do
              = prepend_icon :plus, translate('helpers.links.new', model: Image::ShopLink.model_name.human)